### ISSUE TITLE
remove satellite data

### ISSUE THREAD

**Issue by MeganRSullivan** [fprimeau/OCIM-BGC#10]
Hi @fprimeau and @Hojongseo, we should remove the satellite data files from the repository. I think they are contributing to how slow it is to push/pull from origin and switch between branches.

**Comment by Hojongseo** [comment]
Sure, I will remove the raw data of observation (e.g., satellite, WOA, GLODAP...). You can find all data files for 48layer model include satellite data in my DFS-L directory (/DFS-L/DATA/primeau/hojons1/OCIM-BGC/Observation_rawdata). We should move this data files to google drive or dropbox as we talk yesterday.
